# Generated by Django 6.0.4 on 2026-04-25 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва валюти')),
                ('buy_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс купівлі')),
                ('sell_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс продажу')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Курс валюти',
                'verbose_name_plural': 'Курси валют',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='Дата')),
                ('buy_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс купівлі')),
                ('sell_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс продажу')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='exchange.currencyrate')),
            ],
            options={
                'verbose_name': 'Збережений курс',
                'verbose_name_plural': 'Збережені курси',
                'ordering': ['currency__name'],
                'unique_together': {('currency', 'snapshot_date')},
            },
        ),
    ]
